## Pandas

### Series and Dataframes

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([2,4,5,7,8])
s1

0    2
1    4
2    5
3    7
4    8
dtype: int64

In [3]:
s1[s1>=5]

2    5
3    7
4    8
dtype: int64

In [4]:
s1>=5

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [5]:
data = {"a":99,"b":87,"c":11,"d":77,"e":90}
data

{'a': 99, 'b': 87, 'c': 11, 'd': 77, 'e': 90}

In [6]:
s4 = pd.Series(data)
s4

a    99
b    87
c    11
d    77
e    90
dtype: int64

In [7]:
print(s4[1])

87

C:\Users\alkap\AppData\Local\Temp\ipykernel_47172\4195259936.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s4[1])

In [8]:
print(s4[1:4])

b    87
c    11
d    77
dtype: int64

In [9]:
print(s4.loc["a":"e"]) #loc is used when you want to access elements by location labels

a    99
b    87
c    11
d    77
e    90
dtype: int64

In [10]:
print(s4.iloc[1:4]) #iloc is used for index location acess

b    87
c    11
d    77
dtype: int64

In [11]:
print(s4.loc["e"])

90

In [12]:
print(s4.iloc[4])

90

In [13]:
# filter operation or subsetting

hello1 = pd.Series([1,2,3,4,6,7,8,33,55,99,7,3,22,11,66,5,4323,12,21])
print(hello1)

0        1
1        2
2        3
3        4
4        6
5        7
6        8
7       33
8       55
9       99
10       7
11       3
12      22
13      11
14      66
15       5
16    4323
17      12
18      21
dtype: int64

In [14]:
hellofiltered = hello1[hello1>8]
hellofiltered

7       33
8       55
9       99
12      22
13      11
14      66
16    4323
17      12
18      21
dtype: int64

In [15]:
#reset index

hellofiltered.reset_index(drop=True)

0      33
1      55
2      99
3      22
4      11
5      66
6    4323
7      12
8      21
dtype: int64

In [16]:
sum(hellofiltered)

4642

In [17]:
# create a dataframe:

data = {"Name":["Abc","xyz","pqr","sth"],"Age":[12,14,20,30],"City":["Delhi","Mumbai","Lucknow","Chennai"]}

df = pd.DataFrame(data)

In [18]:
df.describe()

             Age
count   4.000000
mean   19.000000
std     8.082904
min    12.000000
25%    13.500000
50%    17.000000
75%    22.500000
max    30.000000

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [20]:
df.isna()

    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [21]:
df.isnull().sum()

Name    0
Age     0
City    0
dtype: int64

In [22]:
df["NewCol"] = df["Age"]+12 #Add a column
df

  Name  Age     City  NewCol
0  Abc   12    Delhi      24
1  xyz   14   Mumbai      26
2  pqr   20  Lucknow      32
3  sth   30  Chennai      42

In [23]:
df["City"] = df["City"].str.lower() #convert into lower case
df

  Name  Age     City  NewCol
0  Abc   12    delhi      24
1  xyz   14   mumbai      26
2  pqr   20  lucknow      32
3  sth   30  chennai      42

In [24]:
#df2 = pd.read_csv("all_batsmen_data.csv")
df2 = pd.read_csv("C:\\Users\\alkap\\Downloads\\AI_Webinars\\Edureka\\PythonForDataScience\\all_batsmen_data.csv")
df2

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Team         200 non-null    object
 1   Player       200 non-null    object
 2   Filter       200 non-null    object
 3   Matches      200 non-null    int64
 4   Runs         200 non-null    int64
 5   Highest      200 non-null    int64
 6   Average      184 non-null    float64
 7   Strike Rate  200 non-null    float64
dtypes: float64(2), int64(3), object(3)
memory usage: 12.6+ KB

In [26]:
df2.isna().sum()

Team            0
Player          0
Filter          0
Matches         0
Runs            0
Highest         0
Average        16
Strike Rate     0
dtype: int64

In [27]:
df2.isnull().sum()

Team            0
Player          0
Filter          0
Matches         0
Runs            0
Highest         0
Average        16
Strike Rate     0
dtype: int64

In [28]:
df2.describe()

          Matches        Runs     Highest     Average  Strike Rate
count  200.000000  200.000000  200.000000  184.000000   200.000000
mean     4.615000   83.075000   36.130000   23.994837   120.013300
std      3.556687   89.368692   25.121076   17.875742    48.964631
min      1.000000    0.000000    0.000000    0.000000     0.000000
25%      1.000000   20.750000   16.750000   11.937500    97.722500
50%      4.000000   50.000000   31.000000   21.090000   119.430000
75%      7.000000  112.000000   52.250000   31.615000   136.645000
max     18.000000  452.000000  118.000000   92.000000   400.000000

In [29]:
df2.head() #top 5 rows

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09

In [30]:
df2.tail() #last 5 rows

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [31]:
df2_clean = df2.dropna()

In [32]:
df2_clean

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [33]:
df2["Average"].mean()

np.float64(23.99483695652174)

In [35]:
df2["Average"] = df2["Average"].fillna(df2["Average"].mean()) #Fill na of Average column with average values of that column
df2

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [36]:
df2["Team"] = df2["Team"].fillna("100")
df2

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [38]:
df2.isnull().sum()

Team           0
Player         0
Filter         0
Matches        0
Runs           0
Highest        0
Average        0
Strike Rate    0
dtype: int64

In [39]:
df2_cleanfill = df2

In [40]:
df2_cleanfill[["Team","Player","Runs"]]

          Team           Player  Runs
0        India     Rohit Sharma    70
1        India     Rohit Sharma    75
2        India     Rohit Sharma   339
3        India     Rohit Sharma   452
4        India     Rohit Sharma   290
..         ...              ...   ...
195  Hong Kong       Aizaz Khan    15
196  Hong Kong       Aizaz Khan    50
197  Hong Kong  Scott McKechnie    29
198  Hong Kong    Yasim Murtaza   151
199  Hong Kong     Ayush Shukla     0

[200 rows x 3 columns]

In [41]:
df2_cleanfill["Team"].unique()

array(['India', 'Pakistan', 'Afghanistan', 'Bangladesh', 'Sri Lanka',
       'Hong Kong'], dtype=object)

In [42]:
df2_cleanfill["Team"].nunique()

6

In [43]:
df2_cleanfill["Team"].value_counts()

Team
Bangladesh     51
India          39
Afghanistan    36
Sri Lanka      33
Pakistan       25
Hong Kong      16
Name: count, dtype: int64

In [44]:
df2_cleanfill

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [45]:
df2_cleanfill["Newcol"] = df2_cleanfill["Runs"]*df2_cleanfill["Matches"]
df2_cleanfill

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate,Newcol
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27,560
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25,150
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93,6102
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40,4972
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09,3770
...,...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00,75
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20,400
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62,232
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86,1208
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00,0

In [52]:
# Rename a column

df2_cleanfill = df2_cleanfill.rename(columns = {"Newcol":"TotalRunsinMatches","Average":"BattingAverage"})
df2_cleanfill

,Team,Player,Filter,Matches,Runs,Highest,BattingAverage,Strike Rate,TotalRunsinMatches
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27,560
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25,150
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93,6102
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40,4972
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09,3770
...,...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00,75
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20,400
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62,232
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86,1208
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00,0

In [53]:
df.rename(columns = {"NewCol":"AgeAfter12years"},inplace=True)
df

  Name  Age     City  AgeAfter12years
0  Abc   12    delhi               24
1  xyz   14   mumbai               26
2  pqr   20  lucknow               32
3  sth   30  chennai               42

In [57]:
# another way to rename:

df.columns = ["Name1","Age1","City","Age12"]
df

  Name1  Age1     City  Age12
0   Abc    12    delhi     24
1   xyz    14   mumbai     26
2   pqr    20  lucknow     32
3   sth    30  chennai     42

In [64]:
gg = df2_cleanfill[df2_cleanfill["Runs"]>=300]
gg

,Team,Player,Filter,Matches,Runs,Highest,BattingAverage,Strike Rate,TotalRunsinMatches
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93,6102
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40,4972
9,India,Virat Kohli,vs Pakistan,7,311,78,77.75,118.25,2177
11,India,Virat Kohli,vs Sri Lanka,7,339,82,84.75,140.60,2373
16,India,Suryakumar Yadav,year 2022,12,428,117,38.90,189.38,5136
154,Sri Lanka,Dasun Shanaka,year 2022,11,308,74,44.00,145.28,3388
161,Sri Lanka,Pathum Nissanka,year 2022,11,326,75,29.63,114.38,3586

In [62]:
df2_cleanfill[["Player"]]

              Player
0       Rohit Sharma
1       Rohit Sharma
2       Rohit Sharma
3       Rohit Sharma
4       Rohit Sharma
..               ...
195       Aizaz Khan
196       Aizaz Khan
197  Scott McKechnie
198    Yasim Murtaza
199     Ayush Shukla

[200 rows x 1 columns]

In [65]:
gg

,Team,Player,Filter,Matches,Runs,Highest,BattingAverage,Strike Rate,TotalRunsinMatches
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93,6102
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40,4972
9,India,Virat Kohli,vs Pakistan,7,311,78,77.75,118.25,2177
11,India,Virat Kohli,vs Sri Lanka,7,339,82,84.75,140.60,2373
16,India,Suryakumar Yadav,year 2022,12,428,117,38.90,189.38,5136
154,Sri Lanka,Dasun Shanaka,year 2022,11,308,74,44.00,145.28,3388
161,Sri Lanka,Pathum Nissanka,year 2022,11,326,75,29.63,114.38,3586

In [68]:
gg.loc[2]

Team                         India
Player                Rohit Sharma
Filter                vs Sri Lanka
Matches                         18
Runs                           339
Highest                        118
BattingAverage               21.18
Strike Rate                 138.93
TotalRunsinMatches            6102
Name: 2, dtype: object

In [76]:
df2_cleanfill.iloc[0:5]

,Team,Player,Filter,Matches,Runs,Highest,BattingAverage,Strike Rate,TotalRunsinMatches
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27,560
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25,150
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93,6102
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40,4972
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09,3770

In [77]:
df4 = pd.DataFrame({"Name":["A","B","C"],"Age":[22,33,44],"City":["NY","LA","Delhi"]})
df4

  Name  Age   City
0    A   22     NY
1    B   33     LA
2    C   44  Delhi

In [78]:
new_row = {"Name":"Newname","Age":15,"City":"Kolkata"}
new_row

{'Name': 'Newname', 'Age': 15, 'City': 'Kolkata'}

In [81]:
# Append a row to a dataframe

dfnew = df4._append(new_row,ignore_index=True)
dfnew

      Name  Age     City
0        A   22       NY
1        B   33       LA
2        C   44    Delhi
3  Newname   15  Kolkata

In [82]:
newrows = pd.DataFrame({"Name":["X","Y"],"Age":[21,20],"City":["Abc","xyz"]})
newrows

  Name  Age City
0    X   21  Abc
1    Y   20  xyz

In [83]:
dfnew2 = pd.concat([df4,newrows]) #Append one dataframe to another
dfnew2

  Name  Age   City
0    A   22     NY
1    B   33     LA
2    C   44  Delhi
0    X   21    Abc
1    Y   20    xyz

In [84]:
dfnew2.reset_index(drop=True)

  Name  Age   City
0    A   22     NY
1    B   33     LA
2    C   44  Delhi
3    X   21    Abc
4    Y   20    xyz

### Concat

In [85]:
df1 = pd.DataFrame({"ID":[1,2,3],"Name":["Alice","Bob","Charlie"],"Age":[25,26,30]})
df1

   ID     Name  Age
0   1    Alice   25
1   2      Bob   26
2   3  Charlie   30

In [86]:
df2 = pd.DataFrame({"ID":[4,5,6,7],"Name":["David","Eve","Frank","Gilbert"],"Age":[31,35,32,39]})
df2

   ID     Name  Age
0   4    David   31
1   5      Eve   35
2   6    Frank   32
3   7  Gilbert   39

In [89]:
# STACK DATAFRAMES VERTICALLY WITH CONCAT

stackedvertical = pd.concat([df1,df2],ignore_index=True,axis=0) #axis = 0 indicates to python that stacking should be row wise
stackedvertical

   ID     Name  Age
0   1    Alice   25
1   2      Bob   26
2   3  Charlie   30
3   4    David   31
4   5      Eve   35
5   6    Frank   32
6   7  Gilbert   39

In [90]:
df3 = pd.DataFrame({"ID":[1,2,3,4],"Name":["David","Eve","Frank","Gilbert"]})
df3

   ID     Name
0   1    David
1   2      Eve
2   3    Frank
3   4  Gilbert

In [91]:
df4 = pd.DataFrame({"Age":[31,35,32,39],"Salary":["90k","100k","120k","89k"]})
df4

   Age Salary
0   31    90k
1   35   100k
2   32   120k
3   39    89k

In [92]:
stackedhori = pd.concat([df3,df4],axis=1) #axis = 1 indicates to python that stacking should be column wise
stackedhori

   ID     Name  Age Salary
0   1    David   31    90k
1   2      Eve   35   100k
2   3    Frank   32   120k
3   4  Gilbert   39    89k

### Merge

In [93]:
df5 = pd.DataFrame({"ID":[1,2,3,4],"Name":["Alice","Bob","Charlie","David"],"Salary":["25k","26k","30k","40k"]})
df5

   ID     Name Salary
0   1    Alice    25k
1   2      Bob    26k
2   3  Charlie    30k
3   4    David    40k

In [102]:
df6 = pd.DataFrame({"ID":[3,4,5,6],"Name":["Charlie","David","Eve","Frank"],"Age":[40,45,42,49]})
df6

   ID     Name  Age
0   3  Charlie   40
1   4    David   45
2   5      Eve   42
3   6    Frank   49

In [103]:
# inner join - common for both dataframes:

innerj = pd.merge(df5,df6,how="inner",on="ID")
innerj

   ID   Name_x Salary   Name_y  Age
0   3  Charlie    30k  Charlie   40
1   4    David    40k    David   45

In [104]:
innerjclean = innerj.drop(["Name_y"],axis=1)
innerjclean

   ID   Name_x Salary  Age
0   3  Charlie    30k   40
1   4    David    40k   45

In [105]:
innerjclean.columns = ["ID","Name","Salary","Age"]
innerjclean

   ID     Name Salary  Age
0   3  Charlie    30k   40
1   4    David    40k   45

In [106]:
# left join - keep all values from left and match with right:

leftj = pd.merge(df5,df6,how="left",on="ID")
leftj

   ID   Name_x Salary   Name_y   Age
0   1    Alice    25k      NaN   NaN
1   2      Bob    26k      NaN   NaN
2   3  Charlie    30k  Charlie  40.0
3   4    David    40k    David  45.0

In [107]:
# right join - keep all values from right and match with left:

rj = pd.merge(df5,df6,how="right",on="ID")
rj

   ID   Name_x Salary   Name_y  Age
0   3  Charlie    30k  Charlie   40
1   4    David    40k    David   45
2   5      NaN    NaN      Eve   42
3   6      NaN    NaN    Frank   49

In [108]:
# right join - both left and right with corresponding match

oj = pd.merge(df5,df6,how="outer",on="ID")
oj

   ID   Name_x Salary   Name_y   Age
0   1    Alice    25k      NaN   NaN
1   2      Bob    26k      NaN   NaN
2   3  Charlie    30k  Charlie  40.0
3   4    David    40k    David  45.0
4   5      NaN    NaN      Eve  42.0
5   6      NaN    NaN    Frank  49.0

In [109]:
oj.dropna()

   ID   Name_x Salary   Name_y   Age
2   3  Charlie    30k  Charlie  40.0
3   4    David    40k    David  45.0

In [110]:
# Pivot Table

df = pd.DataFrame({"A":["Peter","David","Eve","Frank","Alex","Bob","David","Peter","Mina","Eve"],"B":[20,10,22,33,40,50,90,80,10,47]})
df

       A   B
0  Peter  20
1  David  10
2    Eve  22
3  Frank  33
4   Alex  40
5    Bob  50
6  David  90
7  Peter  80
8   Mina  10
9    Eve  47

In [113]:
pd.pivot_table(df,index=["A"],values="B",aggfunc="sum")

         B
A
Alex    40
Bob     50
David  100
Eve     69
Frank   33
Mina    10
Peter  100

In [114]:
import pandas as pd

data = {
    'Region': ['North', 'North', 'South', 'South', 'East', 'East', 'West', 'West'],
    'Product': ['Laptop', 'Mobile', 'Laptop', 'Mobile', 'Laptop', 'Mobile', 'Laptop', 'Mobile'],
    'Sales': [50000, 30000, 45000, 25000, 40000, 22000, 35000, 28000],
    'Quantity': [10, 15, 8, 12, 9, 11, 7, 14]
}

df = pd.DataFrame(data)

print(df)

  Region Product  Sales  Quantity
0  North  Laptop  50000        10
1  North  Mobile  30000        15
2  South  Laptop  45000         8
3  South  Mobile  25000        12
4   East  Laptop  40000         9
5   East  Mobile  22000        11
6   West  Laptop  35000         7
7   West  Mobile  28000        14

In [115]:
# Sum of sales by Region:

pd.pivot_table(
    df,
    index='Region', #The column you want to see in rows
    values='Sales', #The value you want to aggregate
    aggfunc='sum' #The function to aggregate on
)

        Sales
Region
East    62000
North   80000
South   70000
West    63000

In [116]:
# Sales by Region and product

pd.pivot_table(
    df,
    index='Region',
    columns='Product',
    values='Sales',
    aggfunc='sum'
)

Product  Laptop  Mobile
Region
East      40000   22000
North     50000   30000
South     45000   25000
West      35000   28000

In [117]:
# Sales by Region and product

pd.pivot_table(
    df,
    index=['Region','Product'],
    values='Sales',
    aggfunc='sum'
)

                Sales
Region Product
East   Laptop   40000
       Mobile   22000
North  Laptop   50000
       Mobile   30000
South  Laptop   45000
       Mobile   25000
West   Laptop   35000
       Mobile   28000

In [118]:
# Multiple Aggregations:

pd.pivot_table(
    df,
    index='Region',
    values='Sales',
    aggfunc=['sum', 'mean', 'max']
)

          sum     mean    max
        Sales    Sales  Sales
Region
East    62000  31000.0  40000
North   80000  40000.0  50000
South   70000  35000.0  45000
West    63000  31500.0  35000

In [119]:
# Multiple values to aggregate:

pd.pivot_table(
    df,
    index='Region',
    values=['Sales', 'Quantity'],
    aggfunc='sum'
)

        Quantity  Sales
Region
East          20  62000
North         25  80000
South         20  70000
West          21  63000

In [122]:
# Iterate over dataframes:

for k,v in rj.items():
    print("Key is:",k)
    print("Value is:")
    print(v)

Key is: ID
Value is:
0    3
1    4
2    5
3    6
Name: ID, dtype: int64
Key is: Name_x
Value is:
0    Charlie
1      David
2        NaN
3        NaN
Name: Name_x, dtype: object
Key is: Salary
Value is:
0    30k
1    40k
2    NaN
3    NaN
Name: Salary, dtype: object
Key is: Name_y
Value is:
0    Charlie
1      David
2        Eve
3      Frank
Name: Name_y, dtype: object
Key is: Age
Value is:
0    40
1    45
2    42
3    49
Name: Age, dtype: int64

In [123]:
# Iterate over dataframes in row-wise with iter rows:

for k,v in rj.iterrows():
    print("Key is:",k)
    print("Value is:")
    print(v)

Key is: 0
Value is:
ID              3
Name_x    Charlie
Salary        30k
Name_y    Charlie
Age            40
Name: 0, dtype: object
Key is: 1
Value is:
ID            4
Name_x    David
Salary      40k
Name_y    David
Age          45
Name: 1, dtype: object
Key is: 2
Value is:
ID          5
Name_x    NaN
Salary    NaN
Name_y    Eve
Age        42
Name: 2, dtype: object
Key is: 3
Value is:
ID            6
Name_x      NaN
Salary      NaN
Name_y    Frank
Age          49
Name: 3, dtype: object

In [129]:
# Iterate over dataframes in row-wise with iter tuples:

for t in rj.itertuples():
    print(t)

Pandas(Index=0, ID=3, Name_x='Charlie', Salary='30k', Name_y='Charlie', Age=40)
Pandas(Index=1, ID=4, Name_x='David', Salary='40k', Name_y='David', Age=45)
Pandas(Index=2, ID=5, Name_x=nan, Salary=nan, Name_y='Eve', Age=42)
Pandas(Index=3, ID=6, Name_x=nan, Salary=nan, Name_y='Frank', Age=49)

### Groupby function:

In [130]:
df

  Region Product  Sales  Quantity
0  North  Laptop  50000        10
1  North  Mobile  30000        15
2  South  Laptop  45000         8
3  South  Mobile  25000        12
4   East  Laptop  40000         9
5   East  Mobile  22000        11
6   West  Laptop  35000         7
7   West  Mobile  28000        14

In [132]:
df.groupby("Region")["Sales"].sum().reset_index()

  Region  Sales
0   East  62000
1  North  80000
2  South  70000
3   West  63000

In [137]:
import numpy as np
df.groupby("Region").agg(Total_sales = ("Sales",sum), Average_Quantity = ("Quantity",np.mean))

C:\Users\alkap\AppData\Local\Temp\ipykernel_47172\953168713.py:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby("Region").agg(Total_sales = ("Sales",sum), Average_Quantity = ("Quantity",np.mean))
C:\Users\alkap\AppData\Local\Temp\ipykernel_47172\953168713.py:2: FutureWarning: The provided callable <function mean at 0x000001CB56AFF9C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby("Region").agg(Total_sales = ("Sales",sum), Average_Quantity = ("Quantity",np.mean))

        Total_sales  Average_Quantity
Region
East          62000              10.0
North         80000              12.5
South         70000              10.0
West          63000              10.5