## Pandas

### Series and Dataframes

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([2,4,5,7,8])
s1

0    2
1    4
2    5
3    7
4    8
dtype: int64

In [5]:
s1[s1>=5]

2    5
3    7
4    8
dtype: int64

In [6]:
s1>=5

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [15]:
# create a dataframe:

data = {"Name":["Abc","xyz","pqr","sth"],"Age":[12,14,20,30],"City":["Delhi","Mumbai","Lucknow","Chennai"]}

df = pd.DataFrame(data)

In [16]:
df.describe()

             Age
count   4.000000
mean   19.000000
std     8.082904
min    12.000000
25%    13.500000
50%    17.000000
75%    22.500000
max    30.000000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [18]:
df.isna()

    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [27]:
df.isnull().sum()

Name    0
Age     0
City    0
dtype: int64

In [30]:
df["NewCol"] = df["Age"]+12
df

  Name  Age     City  NewCol
0  Abc   12    Delhi      24
1  xyz   14   Mumbai      26
2  pqr   20  Lucknow      32
3  sth   30  Chennai      42

In [32]:
df["City"] = df["City"].str.lower()
df

  Name  Age     City  NewCol
0  Abc   12    delhi      24
1  xyz   14   mumbai      26
2  pqr   20  lucknow      32
3  sth   30  chennai      42

In [22]:
#df2 = pd.read_csv("all_batsmen_data.csv")
df2 = pd.read_csv("C:\\Users\\alkap\\Downloads\\AI_Webinars\\Edureka\\PythonForDataScience\\all_batsmen_data.csv")
df2

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [21]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Team         200 non-null    object
 1   Player       200 non-null    object
 2   Filter       200 non-null    object
 3   Matches      200 non-null    int64
 4   Runs         200 non-null    int64
 5   Highest      200 non-null    int64
 6   Average      184 non-null    float64
 7   Strike Rate  200 non-null    float64
dtypes: float64(2), int64(3), object(3)
memory usage: 12.6+ KB

In [24]:
df2.isna().sum()

Team            0
Player          0
Filter          0
Matches         0
Runs            0
Highest         0
Average        16
Strike Rate     0
dtype: int64

In [25]:
df2.isnull().sum()

Team            0
Player          0
Filter          0
Matches         0
Runs            0
Highest         0
Average        16
Strike Rate     0
dtype: int64

In [26]:
df2.describe()

          Matches        Runs     Highest     Average  Strike Rate
count  200.000000  200.000000  200.000000  184.000000   200.000000
mean     4.615000   83.075000   36.130000   23.994837   120.013300
std      3.556687   89.368692   25.121076   17.875742    48.964631
min      1.000000    0.000000    0.000000    0.000000     0.000000
25%      1.000000   20.750000   16.750000   11.937500    97.722500
50%      4.000000   50.000000   31.000000   21.090000   119.430000
75%      7.000000  112.000000   52.250000   31.615000   136.645000
max     18.000000  452.000000  118.000000   92.000000   400.000000

In [36]:
df2.head() #top 5 rows

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09

In [34]:
df2.tail() #last 5 rows

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [38]:
df2_clean = df2.dropna()

In [39]:
df2_clean

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [40]:
df2["Average"].mean()

np.float64(23.99483695652174)

In [42]:
df2_cleanfill["Average"] = df2.fillna(df2["Average"].mean())
df2_cleanfill

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [43]:
df2_cleanfill["Team"] = df2_cleanfill["Team"].fillna("100")
df2_cleanfill

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [44]:
df2_cleanfill["Final"] = df2_cleanfill["Matches"]*df2_cleanfill["Average"]
df2_cleanfill

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate,Final
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27,112.00
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25,150.00
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93,381.24
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40,451.99
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09,314.08
...,...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00,75.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20,66.64
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62,58.00
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86,172.56
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00,0.00

In [45]:
df2_cleanfill[["Team","Player","Runs"]]

          Team           Player  Runs
0        India     Rohit Sharma    70
1        India     Rohit Sharma    75
2        India     Rohit Sharma   339
3        India     Rohit Sharma   452
4        India     Rohit Sharma   290
..         ...              ...   ...
195  Hong Kong       Aizaz Khan    15
196  Hong Kong       Aizaz Khan    50
197  Hong Kong  Scott McKechnie    29
198  Hong Kong    Yasim Murtaza   151
199  Hong Kong     Ayush Shukla     0

[200 rows x 3 columns]

In [46]:
df2_cleanfill["Team"].unique()

array(['India', 'Pakistan', 'Afghanistan', 'Bangladesh', 'Sri Lanka',
       'Hong Kong'], dtype=object)

In [47]:
df2_cleanfill["Team"].nunique()

6

In [48]:
df2_cleanfill["Team"].value_counts()

Team
Bangladesh     51
India          39
Afghanistan    36
Sri Lanka      33
Pakistan       25
Hong Kong      16
Name: count, dtype: int64